# This workflow will build source and binary distributions based
# on the current repository tag. Artifacts are then uploaded to
# PyPI and a GitHub Release is created.
#

name: Tag when release PR is merged

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  Tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT

    - run:  echo ${{ contains(github.event.pull_request.head.ref, 'release') }}

    - run: |
        BRANCH=${{ github.event.pull_request.head.ref }}
        echo The PR was merged from branch $BRANCH
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - run: |
        VERSION=v${TEST#release_*}
        echo Will tag $VERSION
